name: Manual Hub Benchmark
on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACTIVELOOP_HUB_PASSWORD: ${{ secrets.ACTIVELOOP_HUB_PASSWORD }}
  REPOSITORY_PAT: ${{ secrets.ACTIVELOOP_BOT_PAT }}
jobs:
  benchmark:
    if: ${{ github.repository == 'activeloopai/hub' }}
    runs-on: [looprunner]
    steps:
      - name: Cleans the workspace
        run: rm -rdf baseline-source
      - name: Checkout the Hub baseline source code
        uses: actions/checkout@v2
        with:
          path: baseline-source
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('hub/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Sets up git username
        run: |
          git config --global user.name activeloop-bot
          git config --global user.email bot@activeloop.ai
      - name: Install Baseline Hub
        run: |
          python -m pip install --upgrade pip
          pip install csv2md # Installs csv2md for the last step
          cd baseline-source
          pip install -r hub/requirements/common.txt
          pip install -r hub/requirements/plugins.txt
          pip install -r hub/requirements/tests.txt
          python setup.py install
      - name: Doing the benchmark and publishing results -> Hub baseline version
        run: |
          cd benchmark-source
          export BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///g')
          pip install -r requirements.ci.txt
          python run.py --all --github
          python publish.py ${BRANCH_NAME} --github
