name: Test
on:
  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs if available
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
  full-test:
    name: Full Test
    uses: activeloopai/shared-github-actions/.github/workflows/full_test.yml@auth-rbac
    if: github.repository == 'activeloopai/deeplake'
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.sha }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
      gcp_workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      gcp_sa: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      hub_username: ${{ secrets.ACTIVELOOP_HUB_USERNAME }}
      hub_password: ${{ secrets.ACTIVELOOP_HUB_PASSWORD }}
      kaggle_username: ${{ secrets.KAGGLE_USERNAME }}
      kaggle_key: ${{ secrets.KAGGLE_KEY }}
      oauth_client_id: ${{ secrets.GDRIVE_CLIENT_ID }}
      oauth_client_secret: ${{ secrets.GDRIVE_CLIENT_SECRET }}
      oauth_refresh_token: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
